[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "numpy>=2.1.3",
    "Cython>=3.0.11"
]
build-backend = "setuptools.build_meta"

[project]
name = "financequery"
version = "1.7.0"
authors = [
    { name = "Verdenroz" }
]
description = "Finance API project"
requires-python = ">=3.11"
dependencies = [
    "aiohappyeyeballs>=2.4.3",
    "aiohttp>=3.10.11",
    "fastapi>=0.115.4",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "redis>=5.2.0",
    "requests>=2.32.3",
    "uvicorn>=0.32.0"
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"
